[package]
name = "stencil-render"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
resvg.workspace = true
base64.workspace = true
sha2.workspace = true
serde_json.workspace = true
thiserror.workspace = true
stencil-model = { path = "../stencil-model" }
stencil-layout = { path = "../stencil-layout" }
stencil-text = { path = "../stencil-text" }

[lints]
workspace = true
