[package]
name = "stencil-model"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
thiserror.workspace = true

[dev-dependencies]
jsonschema.workspace = true

[lints]
workspace = true
