[package]
name = "stencil-layout"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
taffy.workspace = true
thiserror.workspace = true
serde.workspace = true
stencil-model = { path = "../stencil-model" }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
